[package]
name = "climake"
description = "The simple, dependency-less cli library âœ¨"
repository = "https://github.com/owez/climake"
readme = "README.md"
license = "MIT"
version = "2.0.0"
authors = ["Owez <root@ogriffiths.com>"]
edition = "2018"
